"""comment

Revision ID: 7cc7b8890478
Revises: 124a8d5f7051
Create Date: 2021-11-24 07:16:27.765862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc7b8890478'
down_revision = '124a8d5f7051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('User', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('User', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('User', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('User', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
