"""db changes

Revision ID: d875f78a0839
Revises: 124a8d5f7051
Create Date: 2021-11-30 10:00:25.397752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd875f78a0839'
down_revision = '124a8d5f7051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('User', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('User', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blacklist', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklist', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('User', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('User', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('User', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
